##################################################
# MICROSERVICIO: ms-empleados
# URL BASE
##################################################

@baseUrl = http://localhost:8001

##################################################
# PROBAR MICROSERVICIO
##################################################

GET {{baseUrl}}/

###

##################################################
# LISTAR EMPLEADOS
##################################################

GET {{baseUrl}}/empleados
Authorization: prueba

###

##################################################
# OBTENER EMPLEADO POR ID
##################################################

GET {{baseUrl}}/empleados/2
Authorization: prueba

###

##################################################
# CREAR EMPLEADO
##################################################

POST {{baseUrl}}/empleados
Content-Type: application/json
Authorization: prueba

{
    "nombres": "Raphael",
    "apellidos": "Silva",
    "documento": "1097496558",
    "correo": "raphael@empresa.com",
    "telefono": "3107361152",
    "cargo": "Gerente",
    "area": "Finanzas",
    "fecha_ingreso": "2026-06-12",
    "estado": "activo"
}

###

##################################################
# ACTUALIZAR EMPLEADO
##################################################

PUT http://localhost:8001/empleados/6
Content-Type: application/json
Authorization: prueba

{
    "cargo": "Jefe de Finanzas",
    "telefono": "3001112233"
}

###

##################################################
# ELIMINAR EMPLEADO
##################################################

DELETE {{baseUrl}}/empleados/6
Authorization: prueba

###